# SPDX-FileCopyrightText: 2025-2026 Igal Alkon
# SPDX-FileCopyrightText: 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-3-Clause

cmake_policy(VERSION 3.31)

# Install dist/ configuration files.
#
# Files in dist/ are written for the default prefix "/". When
# CMAKE_INSTALL_PREFIX is something else, absolute filesystem paths in the
# installed copies are prefixed:
#   pid: /run/microserve/microserve.pid
#   -> pid: /opt/microserve/run/microserve/microserve.pid
#
# HTTP location values ("path: /") are not filesystem paths and are left alone.
# Relative values (error_log: microserve.log) are left alone.
#
# Expected variables (set by the caller):
#   MICROSERVE_DIST_DIR
#   MICROSERVE_SYSCONFDIR
#   MICROSERVE_STAGE_DIR
# CMAKE_INSTALL_PREFIX is the install-time prefix, including --prefix.
# file(INSTALL) applies DESTDIR; paths written into the configs do not.

if(NOT DEFINED MICROSERVE_DIST_DIR OR NOT DEFINED MICROSERVE_SYSCONFDIR)
    message(FATAL_ERROR "microserve install: MICROSERVE_DIST_DIR and MICROSERVE_SYSCONFDIR must be set")
endif()

if(NOT EXISTS "${MICROSERVE_DIST_DIR}")
    message(STATUS "microserve: ${MICROSERVE_DIST_DIR} not found; skipping config install")
    return()
endif()

function(_microserve_normalize_prefix prefix out_var)
    string(REPLACE "\\" "/" prefix "${prefix}")
    if(prefix STREQUAL "")
        set(prefix "/")
    endif()
    if(NOT prefix STREQUAL "/" AND NOT prefix MATCHES "^[A-Za-z]:/$")
        string(REGEX REPLACE "/+$" "" prefix "${prefix}")
        if(prefix MATCHES "^[A-Za-z]:$")
            set(prefix "${prefix}/")
        endif()
    endif()
    set("${out_var}" "${prefix}" PARENT_SCOPE)
endfunction()

function(_microserve_join_prefix prefix path out_var)
    if(prefix STREQUAL "/")
        set("${out_var}" "${path}" PARENT_SCOPE)
        return()
    endif()
    if(prefix MATCHES "/$")
        string(LENGTH "${path}" _len)
        if(_len GREATER 1)
            math(EXPR _len "${_len} - 1")
            string(SUBSTRING "${path}" 1 "${_len}" path)
        else()
            set(path "")
        endif()
        set("${out_var}" "${prefix}${path}" PARENT_SCOPE)
    else()
        set("${out_var}" "${prefix}${path}" PARENT_SCOPE)
    endif()
endfunction()

# Rewrite one YAML line. Non-matching lines are returned unchanged.
function(_microserve_prefix_config_line line prefix out_var)
    set(_out "${line}")
    if(NOT prefix STREQUAL "/"
            AND line MATCHES "^([ \t]*)([A-Za-z_][A-Za-z0-9_-]*)([ \t]*:[ \t]*)(.*)$")
        set(indent "${CMAKE_MATCH_1}")
        set(key "${CMAKE_MATCH_2}")
        set(sep "${CMAKE_MATCH_3}")
        set(raw "${CMAKE_MATCH_4}")
        set(path "")
        set(tail "")
        set(quote "")
        set(matched FALSE)

        if(key STREQUAL "path")
            # HTTP location, not a filesystem path.
        elseif(raw MATCHES "^(/[^ \t\r#]+)([ \t]+#.*)?[ \t]*$")
            set(path "${CMAKE_MATCH_1}")
            set(tail "${CMAKE_MATCH_2}")
            set(matched TRUE)
        elseif(raw MATCHES "^\"(/[^\"]*)\"([ \t]*(#.*)?)[ \t]*$")
            set(path "${CMAKE_MATCH_1}")
            set(tail "${CMAKE_MATCH_2}")
            set(quote "\"")
            set(matched TRUE)
        elseif(raw MATCHES "^'(/[^']*)'([ \t]*(#.*)?)[ \t]*$")
            set(path "${CMAKE_MATCH_1}")
            set(tail "${CMAKE_MATCH_2}")
            set(quote "'")
            set(matched TRUE)
        endif()

        # Skip bare "/" and protocol-relative "//...".
        if(matched AND path MATCHES "^/[^/]")
            _microserve_join_prefix("${prefix}" "${path}" path)
            if(quote STREQUAL "" AND path MATCHES "[][ \t:#\"']")
                set(quote "\"")
                string(REPLACE "\\" "\\\\" path "${path}")
                string(REPLACE "\"" "\\\"" path "${path}")
            endif()
            if(quote STREQUAL "")
                set(_out "${indent}${key}${sep}${path}${tail}")
            else()
                set(_out "${indent}${key}${sep}${quote}${path}${quote}${tail}")
            endif()
        endif()
    endif()
    set("${out_var}" "${_out}" PARENT_SCOPE)
endfunction()

function(_microserve_prefix_config_content content prefix out_var)
    set(_mode "yaml")
    if(ARGC GREATER 3)
        set(_mode "${ARGV3}")
    endif()
    set(nl "\n")
    if(content MATCHES "\r\n")
        set(nl "\r\n")
        string(REPLACE "\r\n" "\n" content "${content}")
    endif()
    string(REPLACE "\r" "\n" content "${content}")

    set(had_trailing FALSE)
    if(content MATCHES "\n$")
        set(had_trailing TRUE)
    endif()

    set(out "")
    set(sep "")
    set(rest "${content}")
    while(TRUE)
        string(FIND "${rest}" "\n" pos)
        if(pos EQUAL -1)
            if(NOT rest STREQUAL "")
                if(_mode STREQUAL "service")
                    _microserve_prefix_service_line("${rest}" "${prefix}" line)
                else()
                    _microserve_prefix_config_line("${rest}" "${prefix}" line)
                endif()
                string(APPEND out "${sep}${line}")
            endif()
            break()
        endif()
        string(SUBSTRING "${rest}" 0 "${pos}" line)
        math(EXPR next "${pos} + 1")
        string(LENGTH "${rest}" rest_len)
        math(EXPR remain "${rest_len} - ${next}")
        if(remain GREATER 0)
            string(SUBSTRING "${rest}" "${next}" "${remain}" rest)
        else()
            set(rest "")
        endif()
        if(_mode STREQUAL "service")
            _microserve_prefix_service_line("${line}" "${prefix}" line)
        else()
            _microserve_prefix_config_line("${line}" "${prefix}" line)
        endif()
        string(APPEND out "${sep}${line}")
        set(sep "\n")
    endwhile()

    if(had_trailing)
        string(APPEND out "\n")
    endif()
    if(nl STREQUAL "\r\n")
        string(REPLACE "\n" "\r\n" out "${out}")
    endif()
    set("${out_var}" "${out}" PARENT_SCOPE)
endfunction()

function(_microserve_prefix_service_value value prefix out_var)
    set(result "")
    set(rest "${value}")
    while(NOT rest STREQUAL "")
        if(rest MATCHES "^([ \t]+)(.*)$")
            string(APPEND result "${CMAKE_MATCH_1}")
            set(rest "${CMAKE_MATCH_2}")
            continue()
        endif()
        if(NOT rest MATCHES "^([^ \t]+)(.*)$")
            string(APPEND result "${rest}")
            break()
        endif()
        set(tok "${CMAKE_MATCH_1}")
        set(rest "${CMAKE_MATCH_2}")
        set(quote "")
        set(bare "${tok}")
        if(tok MATCHES "^\"(.*)\"$")
            set(quote "\"")
            set(bare "${CMAKE_MATCH_1}")
        elseif(tok MATCHES "^'(.*)'$")
            set(quote "'")
            set(bare "${CMAKE_MATCH_1}")
        endif()
        # Absolute filesystem path only. Skip URLs and protocol-relative "//".
        if(bare MATCHES "^/[^/]" AND NOT bare MATCHES "://")
            _microserve_join_prefix("${prefix}" "${bare}" bare)
            if(quote STREQUAL "" AND bare MATCHES "[ \t]")
                set(quote "\"")
            endif()
            if(quote STREQUAL "")
                set(tok "${bare}")
            else()
                set(tok "${quote}${bare}${quote}")
            endif()
        endif()
        string(APPEND result "${tok}")
    endwhile()
    set("${out_var}" "${result}" PARENT_SCOPE)
endfunction()

function(_microserve_prefix_service_line line prefix out_var)
    set(_out "${line}")
    if(NOT prefix STREQUAL "/"
            AND NOT line MATCHES "^[ \t]*#"
            AND NOT line MATCHES "^[ \t]*$")
        if(line MATCHES "^([ \t]*[A-Za-z0-9_.-]+[ \t]*=)(.*)$")
            set(head "${CMAKE_MATCH_1}")
            _microserve_prefix_service_value("${CMAKE_MATCH_2}" "${prefix}" value)
            set(_out "${head}${value}")
        else()
            _microserve_prefix_service_value("${line}" "${prefix}" _out)
        endif()
    endif()
    set("${out_var}" "${_out}" PARENT_SCOPE)
endfunction()

_microserve_normalize_prefix("${CMAKE_INSTALL_PREFIX}" _prefix)

if(IS_ABSOLUTE "${MICROSERVE_SYSCONFDIR}")
    set(_dest "${MICROSERVE_SYSCONFDIR}/microserve")
elseif(_prefix STREQUAL "/")
    set(_dest "/${MICROSERVE_SYSCONFDIR}/microserve")
elseif(_prefix MATCHES "/$")
    set(_dest "${_prefix}${MICROSERVE_SYSCONFDIR}/microserve")
else()
    set(_dest "${_prefix}/${MICROSERVE_SYSCONFDIR}/microserve")
endif()

set(_unit_rel "lib/systemd/system")
if(_prefix STREQUAL "/")
    set(_unit_dest "/${_unit_rel}")
elseif(_prefix MATCHES "/$")
    set(_unit_dest "${_prefix}${_unit_rel}")
else()
    set(_unit_dest "${_prefix}/${_unit_rel}")
endif()

if(NOT DEFINED MICROSERVE_STAGE_DIR OR MICROSERVE_STAGE_DIR STREQUAL "")
    set(MICROSERVE_STAGE_DIR "${CMAKE_CURRENT_BINARY_DIR}/microserve-dist-install")
endif()
file(REMOVE_RECURSE "${MICROSERVE_STAGE_DIR}")
file(MAKE_DIRECTORY "${MICROSERVE_STAGE_DIR}")

file(GLOB _configs LIST_DIRECTORIES false "${MICROSERVE_DIST_DIR}/*")
list(SORT _configs)

set(_installed 0)
set(_units 0)
foreach(_src IN LISTS _configs)
    get_filename_component(_name "${_src}" NAME)
    if(_name MATCHES "(^\\.)|(~$)|(\\.(bak|orig)$)")
        continue()
    endif()

    set(_file_dest "${_dest}")
    set(_mode "")
    if(_name MATCHES "\\.service$")
        set(_mode "service")
        set(_file_dest "${_unit_dest}")
    elseif(_name MATCHES "\\.(yaml|yml)$")
        set(_mode "yaml")
    endif()

    set(_staged "${_src}")
    if(NOT _mode STREQUAL "" AND NOT _prefix STREQUAL "/")
        file(READ "${_src}" _content)
        _microserve_prefix_config_content("${_content}" "${_prefix}" _content "${_mode}")
        set(_staged "${MICROSERVE_STAGE_DIR}/${_name}")
        file(WRITE "${_staged}" "${_content}")
        message(STATUS "microserve: rewriting absolute paths in ${_name} for prefix ${_prefix}")
    endif()

    file(INSTALL "${_staged}"
            DESTINATION "${_file_dest}"
            PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
    if(_mode STREQUAL "service")
        math(EXPR _units "${_units} + 1")
        message(STATUS "microserve: installed ${_name} to ${_file_dest}")
        if(_prefix MATCHES "^/")
            message(STATUS "microserve: copy the unit into the system unit directory:")
            message(STATUS "  sudo cp \"${_file_dest}/${_name}\" /etc/systemd/system/${_name}")
            message(STATUS "  sudo systemctl daemon-reload")
            message(STATUS "  sudo systemctl enable --now microserve.service")
        else()
            message(STATUS "microserve: unit rewritten for ${_prefix}; on Linux, copy it to /etc/systemd/system")
        endif()
    else()
        math(EXPR _installed "${_installed} + 1")
    endif()
endforeach()

if(_installed EQUAL 0)
    message(STATUS "microserve: no config files to install from ${MICROSERVE_DIST_DIR}")
else()
    message(STATUS "microserve: installed ${_installed} config file(s) to ${_dest}")
endif()